apiVersion: v2
version: 0.9.6
appVersion: 3.8.1
description: A Helm chart for CTFd
name: ctfd
dependencies:
  - name: mariadb
    version: 0.6.0
    repository: oci://registry-1.docker.io/cloudpirates
    condition: mariadb.enabled
  - name: redis
    version: 0.13.1
    repository: oci://registry-1.docker.io/cloudpirates
    condition: redis.enabled
home: https://github.com/bman46/CTFd-Helm
icon: https://raw.githubusercontent.com/CTFd/CTFd/master/CTFd/themes/core/static/img/logo.png
sources:
  - https://github.com/CloudPirates-io/helm-charts
  - https://ctfd.io/
keywords:
  - ctfd
  - ctf
maintainers:
  - name: Brendan McShane
    email: contact@mcshane.systems
