apiVersion: v2
version: 0.6.3
appVersion: 3.7.0
description: A Helm chart for CTFd
name: ctfd
dependencies:
  - name: mariadb
    version: 16.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: redis
    version: 19.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
home: https://github.com/bman46/CTFd-Helm
icon: https://raw.githubusercontent.com/CTFd/CTFd/master/CTFd/themes/core/static/img/logo.png
sources:
  - https://gitlab.com/momothereal/helm-charts
  - https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera
  - https://github.com/bitnami/charts/tree/master/bitnami/redis
  - https://ctfd.io/
keywords:
  - ctfd
  - ctf
maintainers:
  - name: Brendan McShane
    email: contact@mcshane.systems
