{{- if not .Values.env.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ctfd.name" . }}
    helm.sh/chart: {{ include "ctfd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:

{{/* CTFd DB vars:*/}}
{{- $dburl := include "ctfd.DATABASE_URL" . -}}
{{- if not (empty $dburl) }}
  DATABASE_URL: {{ $dburl | b64enc }}
{{- end }}
{{- $redisurl := include "ctfd.REDIS_URL" . -}}
{{- if not (empty $redisurl) }}
  REDIS_URL: {{ $redisurl | b64enc }}
{{- end }}

{{/* User defined secrets:*/}}
{{- range $name, $value := .Values.env.secret }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}