name: helm-dependencies

on:
  # enable manual trigger
  workflow_dispatch:
  schedule:
    # every 12 hours
    - cron: '0 8 * * 1,4'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/helm-dependencies.yml'
      - 'dependencies.yaml'

jobs:
  helm-dependencies:
    name: Helm Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Helm Dependencies
        uses: hckops/actions/helm-dependencies-action@v0.10.6
        with:
          config-path: dependencies.yaml
          user-email: "github-actions@users.noreply.github.com"
          user-name: "github-actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
